import React from "react";
import Header from "../../Header";

const TermsConditions = () => {
    return (
        <div className="text-blue-950 font-roboto min-h-screen">
            {/* Fixed Header */}
            <div className="fixed top-0 left-0 right-0 z-20">
                <Header />
            </div>
            {/* Main Content */}
            <main className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 pt-36 pb-16">
                <section className="max-w-3xl mx-auto space-y-8">
                    <h1 className="text-3xl md:text-4xl font-bold text-orange-500 text-center">
                        Terms and Conditions
                    </h1>

                    <div className="space-y-4 text-justify leading-relaxed">
                        <p>
                            Please read the terms and conditions (&quot;Terms&quot; or &quot;T&amp;C&quot;) carefully. This is a legally
                            binding agreement between you, the user, and Sajan International Private Limited
                            (&quot;Sajan International&quot;) and all its fellow subsidiaries, group companies and permitted
                            assigns establishing the terms and conditions under which this website may be
                            used/accessed.
                        </p>
                        <p>
                            By accessing this website, or any pages thereof, and/or using the information or
                            services provided on or via this website, you agree to be bound by these terms and
                            conditions.
                        </p>
                        <p>
                            In the event you are not agreeable to the T&amp;C, you not access the webstie or avail the
                            services available on the website. The T&amp;C contained herein expressly supersede all
                            prior agreements or arrangements between with Sajan International in relation to
                            the browsing or usage.
                        </p>
                        <p>
                            You further understand that the access to the website and the offer of services is
                            conditional upon your irrevocable consent and acceptance of all the terms,
                            conditions and obligations contained herein (as may be amended from time to
                            time).
                        </p>
                        <p>
                            In the event of any conflict between the terms and conditions of specific products
                            and services and these terms and conditions, the conditions specific to such
                            products and services shall prevail.
                        </p>

                        <h2 className="text-2xl font-semibold text-orange-500 mt-8">General</h2>

                        <p>
                            These Terms , sets forth the terms and conditions that apply to use of this site
                            {/* (www.Sajaninternational.com)  */}
                            {" "}
                            <a
                                href="https://www.sajaninternational.com"
                                target="_blank"
                                rel="noopener noreferrer"
                                className="text-blue-600 underline hover:text-orange-500 transition"
                            >
                                Sajan International
                            </a>
                            {" "}
                            and all sub sites that reside under the site (collectively
                            &#39;Website&#39;), by a Subscriber. The Terms are governed by the provisions of the
                            applicable Indian laws, the rules, regulations, guidelines, and clarifications framed
                            thereunder, including but not limited to:
                        </p>
                        <ul className="list-decimal list-inside ml-4">
                            <li>The Indian Contract Act, 1872;</li>
                            <li>The Information Technology Act, 2000;</li>
                            <li>The Information Technology (Reasonable Security Practices and Procedures and Sensitive Personal Information) Rules, 2011;</li>
                            <li>The Information Technology (Intermediaries Guidelines) Rules, 2011.</li>
                        </ul>

                        <p>
                            These Terms and your activity under these Terms are an electronic record as per the
                            (Indian) Information Technology Act, 2000 and these Terms being electronically
                            generated by a computer system does not require any physical or digital signatures.
                            Under these Terns, &quot;You&quot; means you and every each person who establishes or
                            accesses a connection (&#39;Account&#39;) for access to and use of the Website.
                        </p>

                        <h2 className="text-2xl font-semibold text-orange-500 mt-8">Restrictions on use</h2>
                        <p>
                            The Website are owned and operated by Sajan International Private Limited and
                            contains material which is derived, in whole or in part, from material supplied by the
                            Company, its group companies, various news agencies and other sources (including
                            content partners), and is protected by international copyright and trademark laws.
                            The restrictions on use of the material and content on the Website by the Subscriber
                            are specified below. Except where specifically authorised, the Subscriber may not
                            modify, copy, reproduce, republish, upload, post, transmit or distribute in any way
                            any material from the Website including code and software.
                        </p>
                        <h2 className="text-2xl font-semibold text-orange-500 mt-8">Compliance with the Terms</h2>

                        <p>
                            By using the Website, you agree to comply with all of the terms and conditions
                            hereof. The right to use the Website is personal to you and is not transferable to any
                            other person or entity. You are responsible for all use of your account (under any
                            screen name or password) and for ensuring that all use of your account complies
                            fully with the provisions of this Agreement. You shall be responsible for protecting
                            the confidentiality of your password(s), if any.
                        </p>

                        <h2 className="text-2xl font-semibold text-orange-500 mt-8">Changed Terms</h2>
                        <p>
                            The Company shall have the right at any time to change or modify the terms and
                            conditions applicable to Subscriber&#39;s use of the Website, or any part thereof, or to
                            impose new conditions, including but not limited to, adding fees and charges for
                            use. Such changes, modifications, additions or deletions shall be effective
                            immediately upon notice thereof, which may be given by any means, including but
                            not limited to, posting on the Website, or by electronic or conventional mail, or by
                            any other means by which you obtain notice thereof. Any use of the Website by
                            Subscriber after such notice shall be deemed to constitute acceptance by you of
                            such changes, modifications or additions.
                        </p>
                        <h2 className="text-2xl font-semibold text-orange-500 mt-8">Use of Information and Materials</h2>
                        <p>
                            The content (material, information, data, money market movements, news items,
                            texts, graphics, links etc.) contained on this Website is provided for general
                            information only and should not be used as a basis for making business/commercial
                            decisions. You are advised to exercise due caution and/or seek independent advice
                            before availing any facility or entering into any investment or financial obligation
                            based on the Content contained on this Website.
                        </p>
                        <p>
                            The Content contained on this Website or other terms are provided on an &quot;as is&quot;, &quot;as
                            available&quot; basis and are protected by copyright. You may not distribute the Content
                            to others without the express written consent of Sajan International. You may not
                            copy, download, publish, distribute or reproduce any of the Content contained on
                            this Website in any form without prior permission of Sajan International.
                        </p>
                        <p>
                            The Content on this Website should not be regarded as an offer, solicitation,
                            invitation, advice or recommendation to buy or sell investments, securities or any
                            other instrument or financial products / schemes of Sajan International, or any of its
                            subsidiaries/affiliates. Use of the products or services described on this Website may
                            not be permitted in some countries and if in doubt, you should check with your local
                            regulator or authority before requesting further information on such products/
                            services.
                        </p>
                        <h2 className="text-2xl font-semibold text-orange-500 mt-8">Products</h2>
                        <p>
                            Products and Services are available only at the discretion of Sajan International and
                            its fellow subsidiaries, subject to the individual contractual terms and conditions of
                            products and services on which they are offered and such products and services
                            may be withdrawn or amended at any time without notice. The full range of
                            products or services may not be available in all locations. The user acknowledges
                            that certain functions of this Website would require an active internet connection
                            which can be Wi-Fi or the Local Area Network (LAN) connection. Sajan International
                            and its fellow subsidiaries do not assume any responsibility/liability if the Website is
                            not fully functional due to absence/ insufficiency of the required internet connection.
                        </p>
                        <p>
                            All rates, charges and fees quoted / stated for various financial products and
                            schemes and interest rates cited as examples of rates which may be in effect from
                            time to time are indicative rates only and are subject to change at any time at the
                            sole discretion of Sajan International and its fellow subsidiaries as the case may be,
                            and applicable Indian laws. These charges, fees and rates may change depending
                            upon the assessment made by Sajan International in individual cases upon receiving
                            necessary information and documents.
                        </p>
                        <h2 className="text-2xl font-semibold text-orange-500 mt-8">Indicative Loan Terms</h2>
                        <ul className="list-disc list-inside space-y-2">
                            <li>
                                <strong>Loan:</strong> The Loan provided by Sajan International shall be the amount stated in
                                the sanction letter which shall be strictly in accordance with the terms and
                                conditions mentioned herein and based on other documents executed by
                                you.
                            </li>
                            <li>
                                <strong>Rate of Interest:</strong> The rate of interest will be specified in the sanction letter
                                based upon your risk gradation
                            </li>
                            <li>
                                <strong>Disbursement:</strong> Sajan International will disburse the loan to your designated
                                bank account by way of direct bank transfer via NEFT, IMPS or through such
                                other modes as Sajan International deems fit in its absolute discretion.
                            </li>
                            <li>
                                <strong>Repayment:</strong> You shall pay to Sajan International all instalments, inclusive of
                                interest, on a monthly basis on the Scheduled Due Date, from the first due
                                date to the last due date as mentioned in the Sanction Letter/ loan
                                agreements (as may be required by the Lender to its satisfaction), without fail
                                on the first presentation.
                            </li>
                            <li>
                                In order to facilitate such repayment, Sajan International has provided various
                                options that can be relied upon by you., including, without limitation, debit
                                card payment, Net Banking Payment, direct bank transfer, etc. In order to
                                further secure such payments, Sajan International relies on securest payment
                                gateway like Razorpay.
                            </li>
                        </ul>
                        <p className="mt-4">
                            <strong>Problem with a repayment:</strong> Please talk to our partner on following credentials:
                        </p>
                        <table className="table-auto w-full border-collapse border border-blue-300 mt-4">
                            <thead>
                                <tr className="bg-blue-100">
                                    <th className="border border-blue-300 px-4 py-2 text-left">App</th>
                                    <th className="border border-blue-300 px-4 py-2 text-left">Helpline</th>
                                    <th className="border border-blue-300 px-4 py-2 text-left">Email</th>
                                </tr>
                            </thead>
                            <tbody>
                                <tr>
                                    <td className="border border-blue-300 px-4 py-2">Creditmitra</td>
                                    <td className="border border-blue-300 px-4 py-2">9951703178</td>
                                    <td className="border border-blue-300 px-4 py-2">
                                        <a href="mailto:support@Creditmitra.in" className="text-blue-600 underline">
                                            support@Creditmitra.in
                                        </a>
                                    </td>
                                </tr>
                            </tbody>
                        </table>
                        <p className="mt-4">
                            <strong>Refund:</strong> All refunds in relation to your loan that are initiated by us will be
                            credited to the account/card from where the original transaction had
                            initiated. Such refunds shall be credited within the statutory time period.
                        </p>
                        {/* Equipment */}
                        <div>
                            <h2 className="text-xl font-semibold text-orange-500 mb-2">Equipment</h2>
                            <p>
                                You shall be responsible for obtaining and maintaining all telephone, computer hardware and other equipment needed for access to and use of the Website and all charges related thereto.
                            </p>
                        </div>

                        {/* Intellectual Property Rights */}
                        <div>
                            <h2 className="text-xl font-semibold text-orange-500 mb-2">Intellectual Property Rights</h2>
                            <p>
                                As long as you respect these terms and conditions for browsing/ using this Website, Sajan International grants you a non-exclusive, non-transferable and revocable license to use this Website.
                            </p>
                            <p>
                                All rights relating to this website as well as its functionalities are the exclusive property of Sajan International (particularly including but not limited to copyrights, trademarks, source code, patents as well as any other intellectual property right). All the information provided on or via this Website (including all texts, graphics, design or logos) shall be the intellectual property of Sajan International and or its fellow subsidiaries/ affiliates.
                            </p>
                            <p>
                                You agree not to copy, forward, download or share content without obtaining the necessary rights or permissions to do so. You also agree not to abuse the use of this Website.
                            </p>
                        </div>

                        {/* Limited Use */}
                        <div>
                            <h2 className="text-xl font-semibold text-orange-500 mb-2">Limited Use</h2>
                            <p>While browsing the Website or using any Services provided herein, you agree that you shall not:</p>
                            <ul className="list-decimal list-inside space-y-1 mt-2 pl-2">
                                <li>Use Sajan International's Services for spamming or any other illegal purposes;</li>
                                <li>Infringe Sajan International’s or any third party's intellectual property rights, rights of publicity or privacy;</li>
                                <li>Post or transmit any message, data, image or program which violates any law or which discloses private or personal matters concerning any person;</li>
                                <li>Refuse to cooperate in an investigation or provide confirmation of your identity or any other information you provide to Sajan International;</li>
                                <li>Remove, circumvent, disable, damage or otherwise interfere with security related features of the Sajan International's Services or features that enforce limitations on the use of Sajan International's Services and Website;</li>
                                <li>Upload any content that contains software viruses or any other computer code, files or programs designed to interrupt, destroy or limit the functionality of any computer resource;</li>
                                <li>Reverse engineer, decompile, disassemble or otherwise attempt to discover the source code of Sajan International's Services or any part thereof or infringe any patent, trademark, copyright or other proprietary rights;</li>
                                <li>Use the Services in any manner that could damage, disable, overburden, or impair, including automated usage;</li>
                                <li>
                                    Interfere or disrupt Sajan International’s Services and Services or networks connected in addition to that;
                                    <ul className="list-[lower-roman] list-inside pl-6 space-y-1 mt-1">
                                        <li>Use the facilities and capabilities of Sajan International’s Services and Services to conduct any activity or solicit the performance of any illegal activity or other activity which infringes the rights of others;</li>
                                    </ul>
                                </li>
                                <li>Provide false, inaccurate or misleading information to Sajan International’s Services and Website; and</li>
                                <li>Use Sajan International’s Services and Services to collect or obtain personal information, including without limitation, personal information about other Users of Sajan International’s Services and Website.</li>
                            </ul>
                        </div>

                    </div>
                    <h2 className="text-2xl font-semibold text-orange-500">Linked Websites</h2>
                    <p>This Website may contain links to other websites of affiliate companies or fellow subsidiaries of Sajan International. This Website also contains links to external websites, having further linked websites, controlled or offered by third parties (non-affiliates of Sajan International), in order to help you find relevant websites, services and/or products which may be of interest to you, quickly and easily. The contents displayed or products / services offered on such linked websites or any quality of the products/ services are not endorsed, verified or monitored by Sajan International or its affiliates...</p>

                    <h2 className="text-2xl font-semibold text-orange-500">Data Protection</h2>
                    <p>The storage, usage and transmission of all information obtained by it through the Website, shall at all times be in accordance with the Information Technology Act, 2000 read with Information Technology (Reasonable Security Practices and Procedures and Sensitive Personal Data or Information) Rules, 2011 and all other applicable law. In the event Sajan International obtains any personal data or confidential information pursuant to any transaction/Services, it shall only undertake the processing of Personal Data/Confidential Information reasonably required in connection with the performance of its obligations under the transaction/Services.
                        Sajan International shall at all times have appropriate technical and organisational measures in place to:</p>
                    <ul className="list-decimal list-inside space-y-1 pl-6">
                        <li>prevent unauthorised or unlawful processing of any Personal Data/Confidential Information;</li>
                        <li>protect any Personal Data/Confidential Information against accidental loss, destruction or damage;</li>
                        <li>ensure the reliability of its employees/contractor having access to the Personal Data/Confidential Information;</li>
                    </ul>

                    <h2 className="text-2xl font-semibold text-orange-500">Refund & Cancellation Policy</h2>
                    <p>Any additional payment made by You shall be refunded back within 30 days pursuant to the reconciliation of the accounts by Sajan International.</p>

                    <h2 className="text-2xl font-semibold text-orange-500">
                        Disclaimer of Warranty: Limitation of Liability
                    </h2>

                    <div className="space-y-4 text-justify leading-relaxed text-blue-950">
                        <p>
                            You expressly agree that use of Website is at your sole risk. Neither Sajan International, its affiliates nor any of their respective employees, agents, third party content providers or licensors warrant that Website will be uninterrupted or error free; nor do they make any warranty as to the results that may be obtained from use of Website, or as to the accuracy, reliability or content of any information, service, or merchandise provided through Website.
                        </p>

                        <p>
                            Website is provided on an <span className="italic">&quot;As Is&quot;</span> basis without warranties of any kind, either express or implied, including, but not limited to, warranties of title or implied warranties of merchantability or fitness for a particular purpose, other than those warranties which are implied by and incapable of exclusion, restriction or modification under the laws applicable to this agreement.
                        </p>

                        <p>
                            This disclaimer of liability applies to any damages or injury, caused by any failure of performance, error, omission, interruption, deletion, defect, delay in operation or transmission, computer virus, communication line failure, theft or destruction or unauthorized access to, alteration of, or use of record, whether for breach of contract, tortious behaviour, negligence, or under any other cause of action. In no event will Sajan International, or any person or entity involved in creating, producing or distributing Website or the Website software, be liable for any damages, including, without limitation, direct, indirect, incidental, special, consequential or punitive damages arising out of the use of or inability to use Website. You hereby acknowledge that the provisions of this section shall apply to all content on Website.
                        </p>

                        <p>
                            In addition to the terms set forth above neither Sajan International, nor its affiliates, information providers or content partners shall be liable regardless of the cause or duration, for any errors, inaccuracies, omissions, or other defects in, or inauthenticity of, the information contained within Website, or for any delay or interruption in the transmission thereof to the user, or for any claims or losses arising therefrom or occasioned thereby. None of the foregoing parties shall be liable for any third-party claims or losses of any nature, including, but not limited to, lost profits, punitive or consequential damages. Sajan International, its affiliates, information providers or content partners shall have no liability for investment decisions based on the information provided. Neither the Company, nor its affiliates, information providers or content partners warrant or guarantee the timeliness, sequence, accuracy or completeness of any information.
                        </p>
                    </div>


                    <h2 className="text-2xl font-semibold text-orange-500">Governing Law and Jurisdiction</h2>
                    <p>These Terms will be governed by the laws of the India, without regard to its conflict of laws rules. Any dispute arising on account of the Website of usage of any Services, will be exclusively settled by the courts located in Delhi, India.</p>

                    <h2 className="text-2xl font-semibold text-orange-500">Details of Grievance Redressal Officer</h2>
                    <ul className="list-none space-y-1 pl-0">
                        <p>
                            In accordance with Information Technology Act, 2000 and rules made there under, the name and contact details of the Grievance Officer of Sajan International are as provided below:
                        </p>
                        <li><strong>Name:</strong> </li>
                        <li><strong>Address:</strong> </li>
                        <li><strong>Phone No:</strong> </li>
                        <li><strong>Email id:</strong> </li>
                    </ul>

                    <h2 className="text-2xl font-semibold text-orange-500">Breach of the terms</h2>
                    <p>Without prejudice to Sajan International’s other rights under these Terms, if you breach these Terms in any way, or if Sajan International suspects that you have breached these Terms in any way, then Sajan International shall be entitled to take such action as it may deem fit.</p>
                </section>

            </main>
        </div>
    );
};

export default TermsConditions;
